# window size
remember_window_size no
initial_window_width  1600
initial_window_height 1200
enable_audio_bell no

# font
font_family JetBrainsMonoNL Nerd Font
font_size 18

# misc
confirm_os_window_close 0
background_opacity 0.9

# BEGIN_KITTY_THEME
# Default
include current-theme.conf
# END_KITTY_THEME
